print("🌟hey sweetheart! let's come up with a recipe generator to build us an amazing dish for today's evening meal!🌟🤗")
print("you just have to answer a few questions and we'll be cooking up a storm in no time!")
print()
ingredient = input("name a type of citchen you like the most 🥰")
plant = input("what's your favorite greens?🥗")
cookingMethod = input("what's your favourite cooking method?👩‍🍳🍳🔪")
burnedFoodDescriptiom = input("what's ypur least favourite food?🤐😏?")
householdItem = input("which household item do you use the most?")
print()
print("okay darling, let's get cooing!🥰👩‍🍳")
print("************TODAY'S MENU🌟🌟🌟🌟🌟************")
print("for a dinner we'll have", ingredient, "👩‍🍳🌟   I prepared for you a", cookingMethod, plant, "with a side of", burnedFoodDescriptiom, "which you can it with your favourite", householdItem, "😅💕 he-he, don't forget to share your opinion with me!🥰👩‍🍳")
print("************💕ENJOY YOUR MEAL DARLING!💕************")
print("************🌟PLEASE DON'T FORGET TO RATE IT, THANK YOU!🌟************")
