print("\033[35m","🌙🔮Welcome to the prediction window. I am going to ask you questions about you and tell you your bright future based on your answers. Let's start!🔮🌙", "\033[0m")
print()
name = input("first, tell me your name.")
print("okay", name)
passion = input("what is your passion?")
live = input("how long do you want to live?")
number = input("what's your favourite number?")
kitchen = input("what's your favourite kitchen?")
print("good, thanks for the answers")
print()
print("🌙🔮 NOw let's see your future🔮🌙")
print({name}, "\033[33m", "you will have a great future  in the country where they cook delicious", {kitchen}, "you will live there", {live}, "years, and will start doing your", {passion}, "and will reach the greatest success in your life in", {number}, "years, whole world  is gonna know you, not only your friends or that country, or your family, every single living being will know you and love you","\033[0m")
print()
print("That'll be 20 bucks")
print("see u, bye🌙")
