
print("hey there! what's up?")
print()
herName=input("what is your name?")
print(herName)
favFood=input("what is your favourite food?")
print(favFood)
print("yum!" + favFood + "sounds delicious")
print()
favMusic=input("what is your favourite music?")
print(favMusic)
print("oh really?! I love them too!" + favMusic + "is my favourite band too!")
print()
print("it was nice to talk to you, see you later!")